print ('Oi, mundo')
print('')
print('10')
print('')
print(10)
print('')
print('Este é o programa', 2)
print('')
print('Os números não precisão de aspas, porque o computador sabe representar')
print('um número, mas não letras. A vírgula apresenta acrécimo ')
print('na mensagem de cima.')
print('')
print('Eu tenho',0,'animais... \n Mas isso por enquanto...')
